# Generated by Django 4.1 on 2023-07-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='categorie_image',
            field=models.ImageField(blank=True, null=True, upload_to='categorie'),
        ),
    ]
